- name: 'alpine'
  id: 'test-connectivity'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo "Testing connectivity to GKE API at https://10.92.36.2/version"
      apk add --no-cache curl
      curl -k --connect-timeout 10 https://10.92.36.2/version && echo "Connection success!" || (echo "Connection failed!" && exit 1)
