name: Build and Deploy Go App to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mythic-cocoa-463514-i6
  REGION: us-central1
  ZONE: us-central1-a
  CLUSTER_NAME: standard-cluster-1
  IMAGE_PATH: us-central1-docker.pkg.dev/mythic-cocoa-463514-i6/gcf-artifacts/hello-app

jobs:
  build-deploy:
    name: Build, Scan, Push, and Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker to Google Artifact Registry
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_PATH:latest .

    - name: Run Checkov Scan (Dockerfile)
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        file: Dockerfile
        soft_fail: true

    - name: Push Docker Image
      run: |
        docker push $IMAGE_PATH:latest

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME \
          --zone $ZONE --project $PROJECT_ID

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy via Helm
      run: |
        helm upgrade --install hello-app ./charts/hello-app \
          --set image.repository=$IMAGE_PATH \
          --set image.tag=latest \
          --namespace default \
          --wait

    - name: QA Approval (Manual Step)
      if: always()
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
