gcloud recommender recommendations list \
  --recommender=google.container.DiagnosisRecommender \
  --location=us-east4 \
  --project=YOUR_PROJECT_ID \
  --filter="recommenderSubtype:NODE_SA_MISSING_PERMISSIONS"
