gcloud container clusters describe gpcp2p-q-pymt-use4-gke \
  --region us-east4 \
  --project gpcp2p-q-pymt \
  --format="get(clusterIpv4Cidr, ipAllocationPolicy.podCidr, ipAllocationPolicy.clusterSecondaryRangeName)"
