gcloud compute instances create bastion-vm \
  --project=<HOST_PROJECT_ID> \
  --zone=<ZONE> \
  --machine-type=e2-medium \
  --subnet=<PRIVATE_SUBNET_NAME> \
  --tags=bastion \
  --no-address \  # no public IP, fully private
  --image-family=debian-12 \
  --image-project=debian-cloud \
  --metadata=startup-script='#! /bin/bash
      sudo apt-get update
      sudo apt-get install -y openssh-server'
